---
- name: install NTP on control node
  tags: ntp
  hosts: controlnode
  become: true
  tasks:
    - name: install NTP
      apt:
        name: ntp
        state: present
      tags:
        - ntp

- name: install OpenStack packages on control node
  tags: setup
  hosts: controlnode
  become: true
  tasks:
    - name: install OpenStack packages for controller services
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-openstackclient
        - nova-api
        - nova-scheduler
        - nova-conductor
        - openstack-dashboard
        - rabbitmq-server
        - memcached
        - apache2
        - libapache2-mod-wsgi-py3
        - neutron-server
        - keystone
        - glance
      when: ansible_os_family == 'Debian'
      tags:
        - openstack_packages

- name: install SQL Database on control node
  tags: mysql
  hosts: controlnode
  become: true
  tasks:
    - name: install MySQL server core
      apt:
        name: mysql-server-core-8.0
        state: present
      tags:
        - mysql

    - name: install MySQL server 8.0
      apt:
        name: mysql-server-8.0
        state: present

    - name: start MySQL service
      service:
        name: mysql
        state: restarted
        enabled: yes
      tags:
        - mysql_service

- name: install Message Queue on control node
  tags: rabbit
  hosts: controlnode
  become: true
  tasks:
    - name: install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
      tags:
        - rabbitmq

    - name: start RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - rabbitmq_service

- name: install Memcached on control node
  tags: memcached
  hosts: controlnode
  become: true
  tasks:
    - name: install Memcached
      apt:
        name: memcached
        state: present
      tags:
        - memcached

    - name: start Memcached service
      service:
        name: memcached
        state: started
        enabled: yes
      tags:
        - memcached_service

- name: install and configure Etcd on control node
  tags: etcd
  hosts: controlnode
  become: true
  tasks:
    - name: install Etcd
      apt:
        name: etcd
        state: present
      tags:
        - etcd

    - name: start Etcd service
      service:
        name: etcd
        state: started
        enabled: yes
      tags:
        - etcd_service
